### ISSUE TITLE
Only set motor speed when there is a change to the motor speed

### ISSUE THREAD

**Issue by markwomack** [victoriarobotics/victoria_platform#11]
We call setMotors() for every loop. We should only call it when we have received a cmd_vel or we have not received a cmd_vel for the threshold. That would allow the motor controller hardware to stop itself since it does not get a continuous stream of commands.

**Comment by griswaldbrooks** [comment]
Superfluous?

**Comment by markwomack** [comment]
I guess so, unless we want to add code in doMotorContoller or setMotors that if the new speeds are the same as the current speeds, just ignore it and don't send anything to the trex.

**Comment by griswaldbrooks** [comment]
Ok. Unless this comes up again, I'm closing it.
