### ISSUE TITLE
Use set acceleration for motor speed instead of set speed

### ISSUE THREAD

**Issue by markwomack** [victoriarobotics/victoria_platform#13]
TRex support a set acceleration instead of just set speed. The speed will be brought up to the set acceleration with changes every 10th or 100th of a second. This may make the robot less jumpy when starting up and changing direction, etc.

**Comment by griswaldbrooks** [comment]
Done?

**Comment by markwomack** [comment]
Yes, we are already using the acceleration commands instead of the speed commands.
