### ISSUE TITLE
Publish bumper sensor info

### ISSUE THREAD

**Issue by markwomack** [victoriarobotics/victoria_platform#39]
Need a message with the bumper information raw and/or calculated.

**Comment by markwomack** [comment]
#42

**Comment by markwomack** [comment]
Update bumper message to "BumperDisplacement1D", maybe change field names to match.

**Comment by markwomack** [comment]
DistanceDisplacement1D?

**Comment by griswaldbrooks** [comment]
Sure.

**Comment by markwomack** [comment]
Values will be in meters.

**Comment by markwomack** [comment]
#49
