### ISSUE TITLE
Wire parameters

### ISSUE THREAD

**Issue by griswaldbrooks** [victoriarobotics/victoria_platform#8]
@markwomack 
I can't easily find out what these parameters are
https://github.com/victoriarobotics/victoria_platform/blob/master/Arduino/victoria_teensy_ros_node/victoria_teensy_ros_node.ino#L146

Can we make the magic numbers `const int` with names like `I2C_MASTER_ADDRESS` or whatever they are.

**Comment by markwomack** [comment]
These are coming from header files from the libraries we are using.  Not sure I can easily do this.

**Comment by griswaldbrooks** [comment]
https://github.com/victoriarobotics/victoria_platform/blob/master/Arduino/victoria_teensy_ros_node/victoria_teensy_ros_node.ino#L121

What do you mean?
Why can't we write:
```
// Setup basic I2C master mode pins 18/19, external pullups, 400kHz, 200ms default timeout
const int I2C_WHATEVER_THIS_IS = 0x00;
const int I2C_BUS_SPEED = 400000;
Wire.begin(I2C_MASTER, I2C_WHATEVER_THIS_IS, I2C_PINS_18_19, I2C_PULLUP_EXT, I2C_BUS_SPEED);
```

**Comment by markwomack** [comment]
Yeah, we could, but then we are disconnecting ourselves from the library we are trying to use. I am not sure that is a great strategy. Not like we are using more meaningful names that are adding much, and the comment right above is more informative anyways.

**Comment by griswaldbrooks** [comment]
What do you mean by 
>but then we are disconnecting ourselves from the library we are trying to use

**Comment by markwomack** [comment]
Oh, you are referring to the values that don't already have #defines.  Now this makes more sense.  The original description was not clear, I thought you were referring to all the parameters.

**Comment by griswaldbrooks** [comment]
You're silly @markwomack 
Yes, I was referring to those two magic numbers.

**Comment by markwomack** [comment]
#38
